config/routes.rb
Rails.application.routes.draw do
  resources :blogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def create
    blog = Blog.new(blog_params)
    blog.save
    redirect_to blog_path(blog)
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    blog = Blog.find(params[:id])
    blog.update(blog_params)
    redirect_to blog_path(blog)
  end

  def destroy
    blog = Blog.find(params[:id])
    blog.destroy
    redirect_to blogs_path
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :category, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.haml
%h1
  編集画面
= form_with(model: @blog, local: true) do |f|
  %h4
    タイトル
  = f.text_field :title
  %h4
    カテゴリー
  = f.text_field :category
  %h4
    本文
  = f.text_area :body
  = f.submit "保存"

app/views/blogs/index.html.haml
%header
  %h1.headline
    %a{ href: "#" }
      CARAVAN
  .social
    %i.fab.fa-facebook-square
    %i.fab.fa-twitter-square
    %i.fab.fa-instagram

%nav
  %ul.nav-list
    %li.nav-list-item
      %a{ href: "#" }
        Home
    %li.nav-list-item
      %a{ href: "#" }
        About
    %li.nav-list-item
      %a{ href: "#" }
        Topic

.main-visual
  .main-visual-content
    %p.main-visual-text
      The world is a book
      %br
      and those who do not travel
      %br
      read only one page.
    %p.main-visual-name
      St.Augustine

%main.clearfix
  %section.blog
    %h2.blog-headline
      Recent Blogs
    .blog-box
      - @blogs.each do |blog|
        .blog-item.clearfix
          .blog-image
            = image_tag('img/forest.jpg', class: 'blog-image')
          %section.blog-text
            %h3.blog-text-headline
              = link_to blog.title, blog_path(blog)
            %p.blog-date
              = blog.created_at
            %span.category
              = blog.category
    .pagination
      %p
        <<
      %p
        <
      %p
        1
      %p
        2
      %p
        3
      %p
        >
      %p
        >>
  .sidebar
    %section.popular
      %h2.sidebar-headline
        Popular
      .sidebar-contents
        %p.popular-text
          To solve old problems,
          %br
          study new species
        %p.popular-text
          Why Earth may someday
          %br
          look like Mars
        %p.popular-text
          What will humans look
          %br
          like in 100 years?
        %p.popular-text
          How to grow a forest
          %br
          in your backyard
        %p.popular-text
          How humans could evolve
          %br
          to survive in space
    %section.instagram
      %h2.instagram-headline
        Instagram
      .sidebar-contents.clearfix
        .instagram-box
        .instagram-box
        .instagram-box
        .instagram-box
        .instagram-box
        .instagram-box
    %section.categories
      %h2.categories-headline
        Categories
      .sidebar-contents
        %p.categories-text
          Technology(15)
        %p.categories-text
          Business(23)
        %p.categories-text
          Entertainment(12)
        %p.categories-text
          Nature(32)
        %p.categories-text
          Education(9)
        %p.categories-text
          Adventure(23)
        %p.categories-text
          Communication(14)

%footer
  %p.footer-text
    © All rights reserved by Infratop.Inc.

app/views/blogs/new.html.haml
%h1
  新規投稿
= form_with(model: @blog, local: true) do |f|
  %h4
    タイトル
  = f.text_field :title
  %h4
    カテゴリー
  = f.text_field :category
  %h4
    本文
  = f.text_area :body
  = f.submit "投稿"

app/views/blogs/show.html.haml
%header
  %h1.headline
    = link_to "CARAVAN", blogs_path
  .social
    %i.fab.fa-facebook-square
    %i.fab.fa-twitter-square
    %i.fab.fa-instagram

%nav
  %ul.nav-list
    %li.nav-list-item
      %a{ href: "#" }
        Home
    %li.nav-list-item
      %a{ href: "#" }
        About
    %li.nav-list-item
      %a{ href: "#" }
        Topic

.main-visual
  .main-visual-content
    %p.main-visual-text
      The world is a book
      %br
      and those who do not travel
      %br
      read only one page.
    %p.main-visual-name
      St. Augustine

%main.clearfix
  %section.single-blog
    %h2.blog-headline
      Blog
    %section.blog-box
    %h3.blog-box-headline
      = @blog.title
    .blog-box-content
      %p.category
        = @blog.category
      %p.blog-date
        = @blog.created_at
    = image_tag "img/forest.jpg", class: "single-image"
    %p.single-text
      = @blog.body
    = link_to "編集", edit_blog_path(@blog)
    = link_to "削除", blog_path(@blog), method: :delete
    .author-case.clearfix
      .author-image
      .author-box
        .author-name
          By JOHN SMITH / Photographer
        .author-text
          His black and white landscapes, often captured at times
          %br
          of the day and night when the light is fleeting, or in poor
          %br
          weather conditions, such as rain, fog, or snow, are
          %br
          reminiscent of the calm in a storm all with an ethereal
          %br
          quality.
  .sidebar
    %section.popular
      %h2.sidebar-headline
        Popular
      .sidebar-contents
        %p.pupular-text
          To solve old problems,
          %br
          study new species
        %p.popular-text
          Why Earth may someday
          %br
          look like Mars
        %p.popular-text
          What will humans look
          %br
          like in 100 years?
        %p.popular-text
          How to grow a forest
          %br
          in your backyard
        %p.popular-text
          How humans could evolve
          %br
          to survive in space
    %section.instagram
      %h2.instagram-headline
        Instagram
      .sidebar-contents.clearfix
        .instagram-box
        .instagram-box
        .instagram-box
        .instagram-box
        .instagram-box
        .instagram-box
    %section.caegories
      %h2.categories-headline
        Categories
      .sidebar-contents
        %p.categories-text
          Technology(15)
        %p.categories-text
          Business(23)
        %p.categories-text
          Entertainment(12)
        %p.categories-text
          Nature(32)
        %p.categories-text
          Education(9)
        %p.categories-text
          Adventure(23)
        %p.categories-text
          Communication(14)

%footer
  %p.footer-text
    © All rights reserved by Infratop.Inc

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CARAVAN2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CARAVAN2
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield